/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface NutriScore {
    /**
    * The score
    */
    'score': string;
  }
  interface NutriScoreAttributes extends StencilHTMLAttributes {
    /**
    * The score
    */
    'score'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'NutriScore': Components.NutriScore;
  }

  interface StencilIntrinsicElements {
    'nutri-score': Components.NutriScoreAttributes;
  }


  interface HTMLNutriScoreElement extends Components.NutriScore, HTMLStencilElement {}
  var HTMLNutriScoreElement: {
    prototype: HTMLNutriScoreElement;
    new (): HTMLNutriScoreElement;
  };

  interface HTMLElementTagNameMap {
    'nutri-score': HTMLNutriScoreElement
  }

  interface ElementTagNameMap {
    'nutri-score': HTMLNutriScoreElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
